instance:
  distribution:
    version: "2.x"
  components: # @schema item: string; uniqueItems: true; itemEnum: [source-controller,kustomize-controller,helm-controller,notification-controller,image-reflector-controller,image-automation-controller,source-watcher]
    - source-controller
    - kustomize-controller
    - helm-controller
    - notification-controller
    - image-reflector-controller
    - image-automation-controller
    - source-watcher
  sync:
    kind: GitRepository
    url: "https://github.com/andreistefanciprian/flux-demo"
    ref: "refs/heads/migrate-to-fluxoperator"
    provider: github
    pullSecret: flux-system
    path: "clusters/home"
  kustomize:
    patches:
      - target:
          kind: Deployment
          name: "(kustomize-controller|helm-controller|source-controller|notification-controller)"
        patch: |
          - op: add
            path: /spec/template/spec/containers/0/args/-
            value: --concurrent=10
      - target:
          kind: ServiceAccount
          name: "(source-controller|image-reflector-controller|kustomize-controller)"
        path: _patches/gar-workload-identity.yaml